language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r test_requirements.txt"
# command to run tests
script: nosetests --with-coverage --cover-package=chorddb
after_success:
  - coveralls
